---
- hosts: localhost
  gather_facts: false

  tasks:
    - name: to_datetime
      vars:
        str_sample: "2016-08-14 20:00:12"
        str_year: "2021"
        str_ymdhms: 2021.02.10 09-15-20
        str_jst: Wed Feb 10 09:17:08 JST 2021
      debug:
        msg:
          - "{{ str_sample | to_datetime }}"
          - "{{ str_year | to_datetime('%Y') }}"
          - "{{ str_ymdhms | to_datetime('%Y.%m.%d %H-%M-%S') }}"
          - "{{ str_jst | to_datetime('%a %b %d %H:%M:%S %Z %Y') }}"
