---
- hosts: localhost
  gather_facts: false
  
  tasks:
  - name: dict2items sample
    vars:
      menu:
        curry:
          vegetable:
            - carrot
            - potato
            - onion
          meat:
            - cow
          chicken:
        pasta:
          vegetable:
            - spinach
            - garlic
    debug:
      msg: "{{ menu | dict2items }}"
    #### 実行結果
      # "msg": [
      #     {
      #         "key": "curry",
      #         "value": {
      #             "chicken": null,
      #             "meat": [
      #                 "cow"
      #             ],
      #             "vegetable": [
      #                 "carrot",
      #                 "potato",
      #                 "onion"
      #             ]
      #         }
      #     },
      #     {
      #         "key": "pasta",
      #         "value": {
      #             "vegetable": [
      #                 "spinach",
      #                 "garlic"
      #             ]
      #         }
      #     }
      # ]
