- hosts: localhost
  gather_facts: no

  tasks:
  - name:
    #command: curl https://ifconfig.io/all.json
    command: cat all.json
    register: curl_response
  - name: print curl response
    vars:
      json_data: "{{ curl_response.stdout | from_json }}"
    debug:
      # msg: "{{ curl_response.stdout | from_json }}"
      # msg: "{{ json_data.ip }}"
      msg: "{{ (curl_response.stdout | from_json)['ip'] }}"
      # msg: "{{ curl_response.stdout | from_json | json_query('ip') }}"

  # - name: get json data
  #   ansible.builtin.uri:
  #     url: https://ifconfig.io/all.json
  #   register: uri_response

  # - name: print uri response
  #   debug:
  #     msg: "{{ uri_response.json.ip }}"
