---
- hosts: localhost

  # fatal: [localhost]: FAILED! => 
  #   msg: You need to install "jc" prior to running jc filter
  # require:
  #    pip install jc

  tasks:
    - name: jc parser
      vars:
        # result: "{{ lookup('pipe', 'ps') }}"
        result: "{{ lookup('pipe', 'ps aux') }}"
      debug:
        msg: "{{ result | community.general.jc('ps') }}"
    # filter種別はこちら
    # https://github.com/kellyjonbrazil/jc#parsers

    - name: jc parser free
      vars:
        # free: "{{ lookup('pipe', 'free -h') }}"
        free: "{{ lookup('pipe', 'free') }}"
      debug:
        msg: "{{ free | community.general.jc('free') }}"

    - name: jc parser ss
      vars:
        iptables: "{{ lookup('pipe', 'sudo ss -anpl') }}"
      debug:
        msg: "{{ iptables | community.general.jc('ss') }}"

    - name: jc parser iptables
      vars:
        # iptables: "{{ lookup('pipe', 'sudo iptables -t nat -nL') }}"
        iptables: "{{ lookup('pipe', 'sudo iptables -nL') }}"
      debug:
        msg: "{{ iptables | community.general.jc('iptables') }}"

    - name: jc parser ini
      vars:
        ini: "{{ lookup('file', 'jc-sample.ini') }}"
      debug:
        msg: "{{ ini | community.general.jc('ini') }}"
