---
- hosts: localhost
  gather_facts: false
  vars:
    sample_password: password
    salt: salt_example

  tasks:
    - name: password_hash (sha512)
      debug:
        msg:
        - "{{ sample_password | password_hash }}"
        - "{{ sample_password | password_hash('sha512') }}"
        - "{{ sample_password | password_hash('sha512', salt) }}"
        - "{{ sample_password | password_hash('sha512', 'salt_example') }}"
        - "{{ sample_password | password_hash('sha256') }}"  # ハッシュ方式は'5'
        # - "{{ sample_password | password_hash('blowfish') }}"  #ERROR "crypt.crypt does not support 'bcrypt' algorithm"
        - "{{ sample_password | password_hash('md5') }}"  # ハッシュ方式は'1'
        - "{{ sample_password | password_hash('sha512_crypt') }}" # sha512と同じ

    # フィルタの実体はこちら
    # https://github.com/ansible/ansible/blob/v2.10.5/lib/ansible/plugins/filter/core.py#L266
