- hosts: localhost
  gather_facts: no

  vars:
    hosts:
      - name: web1
        addr: 192.168.2.10
        mask: 255.255.255.0
      - name: web2
        addr: 192.168.2.11
        mask: 255.255.255.0
      - addr: 192.168.2.0
        mask: 255.255.255.0

  tasks:
  - name: split filter sample
    debug:
      msg: '{{ hosts | selectattr("name", "defined") | selectattr("name", "eq", "web1") }}'
