---
- hosts: localhost
  tasks:

  - name: Give me list combo of two lists
    ansible.builtin.debug:
      msg:
      - "{{ [1,2,3,4,5] | zip(['a','b','c','d','e','f']) | list }}"
      - "{{ [1,2,3] | zip(['a','b','c','d','e','f']) | list }}"
      - "{{ [1,2,3] | zip(['a','b']) | list }}"
    ### result
    ### 2つの配列要素に対して、それぞれの配列の各インデックスの要素2つずつを要素にもつ配列になる (語彙力)
    # ok: [localhost] => changed=false 
    #   msg:
    #   - - - 1
    #       - a
    #     - - 2
    #       - b
    #     - - 3
    #       - c
    #     - - 4
    #       - d
    #     - - 5
    #       - e
    #   - - - 1
    #       - a
    #     - - 2
    #       - b
    #     - - 3
    #       - c
    #   - - - 1
    #       - a
    #     - - 2
    #       - b
