---
- hosts: localhost
  gather_facts: false

  tasks:
    - name: run container
      community.docker.docker_container:
        name: run-by-ansible
        image: centos:7
        # state: present
        command: tail -f /dev/null

        volumes:
          - data:/volume-data
          - develop:/develop

    - name: run container
      community.docker.docker_container:
        name: mount-from-sample
        image: python:3
        command: python -m http.server 8080

        volumes_from:
          - run-by-ansible
