---
- name : create instances
  collections:
    - oracle.oci
  connection: local
  hosts: localhost

  vars:
    instance_compartment: "{{ lookup('env', 'OCI_COMPARTMENT') | regex_replace('\"', '') }}"
    # 環境変数 OCI_COMPARTMENT にテナンシーのコンパートメントOCIDをセットしておく
    # oci iam compartment list --query 'data[0]."compartment-id"'
    # または、$HOME/.oci/config のtenancy行に記載
    instance_image: ocid1.image.oc1.iad.aaaaaaaaqdc7jslbtue7abhwvxaq3ihvazfvihhs2rwk2mvciv36v7ux5sda
    #### Oracle-Linux-7.9-2021.01.12-0 @ us-ashburn-1
    # oci compute image list -c $OCI_COMPARTMENT
    # または下記一覧などから選択
    # https://docs.oracle.com/en-us/iaas/images/image/b6a7b057-03a8-4624-b08b-c12caa2c63a0/
    # Free Tierで使えるものを選ぶ必要がある。。「インスタンス作成」の画面で確認するしかない？

  tasks:
  - name: List availbility domains
    # 利用可能可用性ゾーンの取得
    # https://github.com/oracle/oci-ansible-collection/blob/v2.13.0/samples/compute/always_free_launch_compute_instance/setup.yaml#L16-L23
    oci_identity_availability_domain_facts:
      compartment_id: "{{ instance_compartment }}"
    register: result
  - set_fact:
      availability_domains: "{{ result.availability_domains }}"


  - name: Create VCN
    oci_network_vcn:
      compartment_id: "{{ instance_compartment }}"
      cidr_block: "10.0.0.0/16"
    register: result
  - set_fact:
      vcn_id: "{{ result.vcn.id }}"

  - name: Create Route Table
    # https://github.com/oracle/oci-ansible-collection/blob/master/docs/collections/oracle/oci/oci_network_route_table_module.rst
    oci_network_route_table:
      compartment_id: "{{ instance_compartment }}"
      # name: route_sample  # name未指定だとデフォルトのルートテーブルになるっぽい？
    register: result
  - set_fact:
      rt_id: "{{ result.route_table.id }}"

  - name: Create a subnet
    # https://github.com/oracle/oci-ansible-collection/blob/master/docs/collections/oracle/oci/oci_network_subnet_module.rst
    oci_network_subnet:
      display_name: subnet_sample
      cidr_block: 10.0.2.0/24
      # availability_domain: "{{ availability_domains[0].name }}" # セットしてるとサブネットタイプが「リージョナル」でなくなる
      compartment_id: "{{ instance_compartment }}"
      route_table_id: "{{ rt_id }}"
      vcn_id: "{{ vcn_id }}"
    register: result
  - set_fact:
      instance_subnet_id: "{{ result.subnet.id }}"


  - name: create instance
    # https://github.com/oracle/oci-ansible-collection/blob/master/docs/collections/oracle/oci/oci_compute_instance_module.rst
    oci_compute_instance:
      display_name: sample_instance1
      availability_domain: "{{ availability_domains[0].name }}"
      compartment_id: "{{ instance_compartment }}"
      shape: VM.Standard.E2.1.Micro
      create_vnic_details:
        subnet_id: "{{ instance_subnet_id }}"
      source_details:
        image_id: "{{ instance_image }}"
        source_type: image
    register: result
    # TASK [create instance] ***********************************************************************************************************************
    # fatal: [localhost]: FAILED! => changed=false 
    #   msg: shape VM.Standard.E2.1.Micro not found