- hosts: localhost
  gather_facts: no

  tasks:
  - name: debug
    debug:
      msg: hello

  - name: create file
    file:
      path: /var/tmp/zzz
      state: directory
      mode: '0755'

  - name: exec my module
    mymodule:
      param: foo
      state: present
      param2: hoge hoge
      values:
        - item1
        - item2
        - item3
      dict:
        host: cloud-dev
        mem: 8
        cpu: 8
        foo: bar
      #failed: true
      failed: false
