---
- hosts: localhost
  gather_facts: false
  
  tasks:
  - name: load ssh public key
    vars:
      pubkey: "{{ lookup('file', '~/.ssh/id_rsa.pub') }}"
    debug:
      msg: "{{ pubkey }}"

  - name: load ssh public key (with env home)
    vars:
      pubkey: "{{ lookup('file', lookup('env', 'HOME') + '/.ssh/id_rsa.pub') }}"
    debug:
      msg: "{{ pubkey }}"
