---
- hosts: localhost
  gather_facts: true
  gather_subset: min
  vars:
    date_str: "{{ lookup('pipe', 'date +%Y/%m/%d_%H:%M:%S.%N') }}"

  tasks:
  - name: print date_str 1
    debug:
      msg: '{{ date_str }}'

  - name: get date
    vars:
      current_date: "{{ lookup('pipe', 'date +%Y/%m/%d_%H:%M:%S') }}"
      # https://docs.ansible.com/ansible/latest/collections/ansible/builtin/pipe_lookup.html
      # pipeを使うとコマンド実行結果を取得できる

    debug:
      msg:
      - "{{ current_date }}"

  - debug:
      msg: "{{ ansible_date_time }}"

  - name: print date_str 2
    debug:
      msg: '{{ date_str }}'
