---
- hosts: localhost
  gather_facts: false

  tasks:
  - name: url lookup plugin
    vars:
      response: "{{ lookup('url', 'https://www.jma.go.jp/bosai/forecast/data/overview_forecast/130000.json') }}"
    debug:
      # msg: "{{ lookup('url', 'https://www.jma.go.jp/bosai/forecast/data/overview_forecast/130000.json', wantlist=true) }}"
      msg: "{{ response.text }}"
