---
- hosts: localhost
  gather_facts: false

  vars:
    netbox_url: http://192.168.0.18:8000/
    netbox_token: 0123456789abcdef0123456789abcdef01234567

    site:
      name: sample site
      slug: sample-slug
    device_role:
      name: sample dev role
      slug: sample-dev-role
    manufacturer:
      name: sample manufacturer
      slug: sample-manufacturer
    device_type:
      model: sample dev type
      slug: sample-dev-type
      subdevice_role: parent
    device:
      name: sample device
      bay_slot:  # device bay用定義 (スロットの定義)
        - name: slot1
          desc: device slot1]
        - name: slot2
          desc: device slot2
        - name: slot3
          desc: device slot3
        - name: slot4
          desc: device slot4
        - name: slot5
          desc: device slot5
    child_device:
      type:
        model: sample child dev type
        slug: sample-child-dev-type
        subdevice_role: child
      device:
        - name: child_device01
        - name: child_device02
    new_device:
      parent:
        name: parent_dev10
        bay:
          - name: slot1
            dev: child_dev10
          - name: slot2
            dev: child_dev11
      child:
        - name: child_dev10
        - name: child_dev11

  tasks:
    - name: create site
      netbox.netbox.netbox_site:
        netbox_url: "{{ netbox_url }}"
        netbox_token: "{{ netbox_token }}"
        data:
          name: "{{ site.name }}"
          slug: "{{ site.slug }}"

    - name: create device role
      netbox.netbox.netbox_device_role:
        netbox_url: "{{ netbox_url }}"
        netbox_token: "{{ netbox_token }}"
        data:
          name: "{{ device_role.name }}"
          slug: "{{ device_role.slug }}"

    - name: create manufacturers
      netbox.netbox.netbox_manufacturer:
        netbox_url: "{{ netbox_url }}"
        netbox_token: "{{ netbox_token }}"
        data:
          name: "{{ manufacturer.name }}"
          slug: "{{ manufacturer.slug }}"

    - name: create device type
      netbox.netbox.netbox_device_type:
        netbox_url: "{{ netbox_url }}"
        netbox_token: "{{ netbox_token }}"
        data:
          slug: "{{ device_type.slug }}"
          model: "{{ device_type.model }}"
          manufacturer: "{{ manufacturer.slug }}"
          subdevice_role: "{{ device_type.subdevice_role }}"

    - name: create device
      netbox.netbox.netbox_device:
        netbox_url: "{{ netbox_url }}"
        netbox_token: "{{ netbox_token }}"
        data:
          name: "{{ device.name }}"
          device_type: "{{ device_type.slug }}"
          device_role: "{{ device_role.slug }}"
          site: "{{ site.slug }}"

    # device bayへスロット作成 (子デバイスを登録するための箱の定義)
    # https://netbox.readthedocs.io/en/stable/core-functionality/devices/#device-bays
    # 対象デバイスのdevice typeでparent/childの設定がparentになっている必要がある
    - name: create device bay slot
      netbox.netbox.netbox_device_bay:
        netbox_url: "{{ netbox_url }}"
        netbox_token: "{{ netbox_token }}"
        data:
          device: "{{ device.name }}"
          name: "{{ item.name }}"
          description: "{{ item.desc }}"
        state: present
      loop: "{{ device.bay_slot }}"


    - name: "[[CHILD]] create device type"
      netbox.netbox.netbox_device_type:
        netbox_url: "{{ netbox_url }}"
        netbox_token: "{{ netbox_token }}"
        data:
          slug: "{{ child_device.type.slug }}"
          model: "{{ child_device.type.model }}"
          manufacturer: "{{ manufacturer.slug }}"
          subdevice_role: "{{ child_device.type.subdevice_role }}"
          u_height: 0

    - name: "[[CHILD]] create device"
      netbox.netbox.netbox_device:
        netbox_url: "{{ netbox_url }}"
        netbox_token: "{{ netbox_token }}"
        data:
          name: "{{ item.name }}"
          device_type: "{{ child_device.type.slug }}"
          device_role: "{{ device_role.slug }}"
          site: "{{ site.slug }}"
      loop: "{{ child_device.device }}"

    # device bayに子デバイス登録
    # 親デバイスのslot[0]に子デバイス[0]をinstall
    - name: set child device to device bay
      netbox.netbox.netbox_device_bay:
        netbox_url: "{{ netbox_url }}"
        netbox_token: "{{ netbox_token }}"
        data:
          device: "{{ device.name }}"
          name: "{{ device.bay_slot[0].name }}"
          installed_device: "{{ child_device.device[0].name }}"
          # installed_device: child_device_xx  # 存在しないデバイスは当然だけど登録不可
        state: present

    # デバイス登録
    - name: create device2
      netbox.netbox.netbox_device:
        netbox_url: "{{ netbox_url }}"
        netbox_token: "{{ netbox_token }}"
        data:
          name: "{{ item.name }}"
          device_type: "{{ item.type }}"
          device_role: "{{ device_role.slug }}"
          site: "{{ site.slug }}"
      loop:
        - name: "{{ new_device.parent.name }}"
          type: "{{ device_type.slug }}"
        - name: "{{ new_device.child[0].name }}" # ズル
          type: "{{ child_device.type.slug }}"   # ズル
        - name: "{{ new_device.child[1].name }}" # ズル
          type: "{{ child_device.type.slug }}"   # ズル
    # デバイスベイ登録(親・子まとめて同時)
    - name: create devicebay with child
      netbox.netbox.netbox_device_bay:
        netbox_url: "{{ netbox_url }}"
        netbox_token: "{{ netbox_token }}"
        data:
          device: "{{ new_device.parent.name }}"
          name: "{{ item.name }}"
          installed_device: "{{ item.dev }}"
        state: present
      loop: "{{ new_device.parent.bay }}"
