---
- name: dynamic inventory sample
  hosts: cluster_vm_network
  gather_facts: false

  tasks:
    - name: ping
      ping:

    - name: print ansible_play_hosts_all
      debug:
        msg: "{{ ansible_play_hosts_all }}"
      run_once: true
