---
- hosts: localhost
  gather_facts: false

  tasks:
    - name: use async
      shell: sleep 5
      async: 8
      poll: 0
      register: result_async

    - name: wait async
      ansible.builtin.async_status:
        jid: "{{ result_async.ansible_job_id }}"
      register: async_poll_results
      until: async_poll_results.finished
      retries: 8
      delay: 1
