---
- hosts: hosts
  gather_facts: false

  tasks:
    - name: sample
      debug:
        msg:
          - "{{ config }}"
          - "{{ list_value }}"
          - "{{ list_value[0] }}"
          - "{{ dict_value }}"
          - "{{ dict_value.shell }}"
          - "{{ dict_value['path'] }}"
