- hosts: localhost
  gather_facts: no

  tasks:
  - name: helm
    community.kubernetes.helm:
      name: mysql-sample
      chart_ref: stable/mysql
      release_namespace: db
      create_namespace: true
      values_files:
      - ./mysql-conf/values-service.yaml
    register: result

  - name: print result
    debug:
      msg: "{{ result }}"
