- hosts: localhost
  gather_facts: no

  tasks:
  - name: Add default repository
    community.kubernetes.helm_repository:
      name: stable
      repo_url: https://kubernetes-charts.storage.googleapis.com

  - name: helm
    community.kubernetes.helm:
      name: mysql-sample
      update_repo_cache: true
      chart_ref: stable/mysql
      release_namespace: db
      create_namespace: true
      # values_files:
      # - ./mysql-conf/values-service.yaml
      release_values:
        service:
          type: NodePort
          port: 3306
    register: result

  - name: print result
    debug:
      msg: "{{ result }}"
