- hosts: localhost
  gather_facts: no

  vars_prompt:
  - name: prompt_value
    prompt: input value
    private: false

  - name: prompt_passwd
    prompt: input password
    private: true
    # privateを有効にするとローカルエコーしない

  tasks:
  - name: prinpt prompt value
    debug:
      msg:
        - "{{ prompt_value }}"
        - "{{ prompt_passwd }}"
    # vars_promptで入力させたデータは文字列。
    # 1 とか入れても文字列の'1'になる。

  # - name: prompt at task
  #   vars_prompt:
  #   - name: task_prompt_value
  #     prompt: input value
  #     private: false
  #   debug:
  #     msg: "{{ task_prompt_value }}"
  #   # task内のvars_promptはエラーになる

  - name: prompt at task
    pause:
      prompt: input value
    register: pause_prompt

  - name: print value by pause+prompt
    debug:
      msg: "{{ pause_prompt }}"

  - name: prompt at task
    pause:
      prompt: input passwd
      echo: false
    register: pause_prompt_passwd

  - name: print value by pause+prompt
    debug:
      msg: "{{ pause_prompt_passwd.user_input }}"