---
- hosts: localhost
  gather_facts: false

  tasks:
  - name: include with loop
    vars:
      users:
        - user1
        - user2
    include_tasks: dup-loop-included.yml
    loop: "{{ users }}"
    loop_control:
      loop_var: item_user
    # 呼び出し先では item_user でループ変数を参照できる。
    # (デフォルトのitemのままだと、呼び出し先でもloopを使うと上書きされる)

#### 実行結果
# TASK [include with loop] *****************************************************************
# included: /home/zaki/src/ansible-sample/loop/dup-loop-included.yml for localhost => (item=user1)
# included: /home/zaki/src/ansible-sample/loop/dup-loop-included.yml for localhost => (item=user2)

# TASK [print] *****************************************************************************
# ok: [localhost] => (item=web1) => 
#   msg: user:user1, server:web1
# ok: [localhost] => (item=web2) => 
#   msg: user:user1, server:web2
# ok: [localhost] => (item=db1) => 
#   msg: user:user1, server:db1

# TASK [print] *****************************************************************************
# ok: [localhost] => (item=web1) => 
#   msg: user:user2, server:web1
# ok: [localhost] => (item=web2) => 
#   msg: user:user2, server:web2
# ok: [localhost] => (item=db1) => 
#   msg: user:user2, server:db1
