- hosts: localhost
  gather_facts: no

  tasks:
  - name: assert sample
    vars:
      hoge: "zzz"
      foo: "bar"
      baz: False
    ansible.builtin.assert:
      that:
      - "hoge is defined"
      - foo is defined
      - baz is defined and baz
      fail_msg: "'hoge','bar' must be defined, 'baz' must be true"
    register: assert_result
    # ignore_errors: true

    # ↑ bazは定義されているが評価するとfalseになるためassertは失敗する
    # ansible-playbook で -e baz=hogehoge とか付与すれば通る

  - name: print result
    debug:
      msg: "{{ assert_result }}"
