---
- hosts: all
  gather_facts: false
  vars:
    username: yu_takasaki
    password: erabenaiyo

  tasks:
  # - name: install acl
  #   ansible.builtin.apt:
  #     name:
  #     - acl
  #     update_cache: true
  #   become: true

  - name: create user
    ansible.builtin.user:
      name: "{{ username }}"
      password: "{{ password | password_hash('sha512') }}"
      shell: /bin/bash
      home: "/home/{{ username }}"
      groups:
      - nijigasaki
    become: true

  - name: create venv
    ansible.builtin.pip:
      name:
      - pip
      - ansible-core==2.18.5
      virtualenv: "/home/{{ username }}/python-env"
      virtualenv_command: python3 -m venv
    become: true
    become_user: "{{ username }}"
    become_method: sudo
    vars:
      ansible_become_password: "{{ password }}"
      ansible_common_remote_group: nijigasaki
      # ansible_remote_user: "{{ username }}"
      # ansible_shell_allow_world_readable_temp: true
    # remote_user: "{{ username }}"
    # vars:
    #   ansible_password: "{{ password }}"
