---
- hosts: localhost
  gather_facts: false
  name: AAP sample

  collections:
  - ansible.platform

  tasks:
  - name: create host
    ansible.platform.user:
      username: "{{ username }}"
      password: "{{ password }}"
      email: "{{ email }}"
      organizations: "{{ organization }}"
      is_superuser: false
      is_platform_auditor: false
