---
- hosts: localhost
  gather_facts: false
  name: AAP sample

  collections:
  - ansible.platform

  tasks:
  - name: create user
    ansible.platform.user:
      username: "{{ username }}"
      password: "{{ password }}"
      email: "{{ email }}"
      # organizations: "{{ organization }}"
      is_superuser: false
      # is_platform_auditor: false

  - name: update user role
    ansible.platform.role_user_assignment:
      user: "{{ username }}"
      role_definition: Organization Member
      object_ids:
      - "{{ organization }}"
