---
- hosts: all
  #gather_facts: true
  gather_facts: false
  become: true

  tasks:
  - name: debug
    debug:
      msg: start ansible!

  - name: install httpd
    yum:
      name:
        - httpd
        - mod_ssl
      state: present

  # - name: enable ssl
  #   community.general.apache2_module:
  #     state: present
  #     name: ssl
  # ^^^ require "a2enmod" but not found on yum/rpm linux

  - name: permit traffic in default zone for https/http
    ansible.posix.firewalld:
      service: "{{ item }}"
      permanent: true
      immediate: true
      state: enabled
    with_items:
      - https
      - http

  - name: start httpd
    service:
      name: httpd
      state: restarted
