---
- hosts: localhost
  gather_facts: false

  roles:
    - role: sample
      tags: __parent_tag
    # __parent_tag 指定時はこのroleが呼ばれ、role内のtaskは全て実行される。
    # __tag1 指定時もこのrole呼び出しは呼ばれ、role内では__tag1のみ実行される。
