---
- hosts: localhost
  gather_facts: false

  tasks:
  - name: log sample
    community.kubernetes.k8s_log:
      host: '{{ api_endpoint }}'
      ca_cert: '{{ ca_cert_filepath }}'
      api_key: '{{ api_key }}'
      namespace: '{{ namespace }}'
      #name: sample-http-6c94f59975-w89gd

      # # nameのかわりにlabel_selectorsでラベル指定
      # label_selectors:
      #   - app=sample-http
      # # 複数podがあっても1個しかlog取れてない気がする

      kind: Pod
      name: '{{ item }}'
    with_items: "{{ lookup('community.kubernetes.k8s', kind='Pod', namespace='rbac-sample', host=api_endpoint, api_key=api_key, ca_cert=ca_cert_filepath) | map(attribute='metadata.name') }}" 
