---
- hosts: server
  gather_facts: false
  become: true

  vars:
    password_plain_str: 'p@ssword!'

  tasks:
  - name: create_user
    ansible.builtin.user:
      name: sample-user
      # パスワード設定に関して：
      # https://docs.ansible.com/ansible/latest/reference_appendices/faq.html#how-do-i-generate-encrypted-passwords-for-the-user-module
      # https://docs.ansible.com/ansible/latest/user_guide/playbooks_filters.html#encrypting-and-checksumming-strings-and-passwords
      password: "{{ password_plain_str | password_hash('sha512') }}"
      # https://github.com/ansible/ansible/blob/v2.10.5/lib/ansible/plugins/filter/core.py#L266
      # ドキュメントに記載はないがhash_type省略時はsha512が使用される

      # state: absent
      # remove: true     # これを追加しないとホームディレクトリなどは残る

    ### result
    # changed: [client-dev] => changed=true 
    #   ansible_facts:
    #     discovered_interpreter_python: /usr/bin/python
    #   comment: ''
    #   create_home: true
    #   group: 1001
    #   home: /home/sample-user
    #   name: sample-user
    #   shell: /bin/bash
    #   state: present
    #   system: false
    #   uid: 1001
