---
- hosts: localhost
  gather_facts: false
  become: true

  tasks:
  - name: cron to user
    ansible.builtin.cron:
      name: sample_cron_conf
      minute: "0"
      hour: "*"
      job: "date >> /tmp/cron-date-test.log"

  - name: cron conf with file
    ansible.builtin.cron:
      name: cron_conf with cron_file
      cron_file: ansible_sample
      minute: "30"
      hour: "*"
      job: "date >> /tmp/cron-date-file.log"
      user: root
      # userは必要:
      # msg: To use cron_file=... parameter you must specify user=... as well
