---
- hosts: localhost
  gather_facts: false

  tasks:
    # ディレクトリ作成
    - name: create directory
      ansible.builtin.file:
        path: /var/tmp/ansible-work
        state: directory
        owner: "{{ lookup('env', 'USER') }}"
        group: "{{ lookup('env', 'USER') }}"  # 暫定

    # symlink作成
    - name: create symlink
      ansible.builtin.file:
        dest: /var/tmp/ansible-work/bin
        src: /usr/local/bin
        state: link

    # 空file作成
    - name: create file
      ansible.builtin.file:
        path: /var/tmp/ansible-work/touch
        state: touch
        # modification_time: "202103311220.01"
        # modification_time: preserve
        # access_time: preserve
