---
- hosts: rhel8
  gather_facts: true
  become: true

  tasks:
    - name: install packaged
      ansible.builtin.dnf:
        name:
          - httpd
          - mod_ssl
        state: present

    - name: start httpd
      ansible.builtin.systemd:
        name: httpd
        state: started
        enabled: true

    - name: firewalld (service)
      ansible.posix.firewalld:
        service: http
        permanent: true
        state: enabled
        immediate: true
      # この時点で設定反映される (immediate)
      # rebootしても有効

    - name: create directory
      ansible.builtin.file:
        state: directory
        path: /var/www/html/sample

    - name: create content
      ansible.builtin.copy:
        dest: /var/www/html/sample/sample.html
        content: |
          <html>
          <body>
          <h1>curry world</h1>
          </body>
          </html>
    # この時点で http://192.168.0.41/sample/sample.html アクセス可能

    - name: wget content
      ansible.builtin.uri:
        url: http://192.168.0.41/sample/sample.html

    - name: create htpaccess
      ansible.builtin.copy:
        dest: /var/www/html/sample/.htaccess
        content: |
          AuthType Basic
          Authname "htpasswd sample"
          AuthUserfile /var/www/html/sample/.htpasswd
          AuthGroupFile /dev/null
          require valid-user

    - name: install passlib
      pip:
        name: passlib
        virtualenv: /root/venv
        virtualenv_command: python3 -m venv

    - name: create htpasswd
      community.general.htpasswd:
        path: /var/www/html/sample/.htpasswd
        name: zaki
        password: 'p@ssw0rd!'
      environment:
        PYTHONPATH: /root/venv/lib/python3.6/site-packages/
