---
- hosts: debian
  gather_facts: true
  become: true

  tasks:
    - name: install packaged
      ansible.builtin.apt:
        name:
          - open-vm-tools
        state: present
      when: ansible_facts.pkg_mgr == 'apt'

    - name: start vmware tools
      ansible.builtin.systemd:
        name: open-vm-tools
        state: started
        enabled: true
