---
- hosts: rhel8
  gather_facts: true
  become: true

  tasks:
    - name: install packaged
      ansible.builtin.dnf:
        name:
          - httpd
          - mod_ssl
        state: present

    - name: start httpd
      ansible.builtin.systemd:
        name: httpd
        state: started
        enabled: true

    - name: firewalld (service)
      ansible.posix.firewalld:
        service: http
        permanent: true
        state: enabled
        immediate: true
      # この時点で設定反映される (immediate)
      # rebootしても有効

    - name: create content
      ansible.builtin.copy:
        dest: /var/www/html/sample.html
        content: |
          <html>
          <body>
          <h1>curry world</h1>
          </body>
          </html>
    # この時点で http://192.168.0.41/sample.html アクセス可能

    - name: wget content
      ansible.builtin.uri:
        url: http://192.168.0.41/sample.html
