---
- hosts: rhel8
  gather_facts: true
  become: true

  tasks:
    - name: install packaged
      ansible.builtin.dnf:
        name:
          - bind
          - bind-utils  # 無くてもいいけどdig使うため
        state: present

    # - name: start bind
    #   ansible.builtin.systemd:
    #     name: named
    #     state: started
    #     enabled: true

    - name: firewalld (service)
      ansible.posix.firewalld:
        service: dns
        permanent: true
        state: enabled
        immediate: true

    - name: create zonefile
      ansible.builtin.template:
        src: templates/named.example.zones.j2
        dest: /etc/named/named.example.zones
        group: named

    - name: append zonefile include
      ansible.builtin.blockinfile:
        path: /etc/named.conf
        marker: // example.org zone {mark}
        block: |
          zone "example.org" {
              type master;
              file "/etc/named/named.example.zones";
          };

    - name: restart bind
      ansible.builtin.systemd:
        name: named
        state: restarted
