---
- hosts: ubuntu
  gather_facts: false
  become: true

  tasks:
    - name: reboot
      ansible.builtin.reboot:
        # reboot_timeout: 600

    - name: command
      command: hostname
      register: result

    - name: print result
      debug:
        msg: '{{ result }}'
