---
- hosts: ubuntu
  gather_facts: false
  become: true

  tasks:
    - name: create netplan configure
      copy:
        dest: /etc/netplan/ens224-config.yaml
        content: |
          network:
            ethernets:
              ens224:
                addresses:
                - 172.16.0.43/23
            version: 2
      # see: man interfaces

    - name: start network
      command: netplan apply
